export const SET_SUBJECT = 'SET_SUBJECT';
export const SET_SUITABILITY = 'SET_SUITABILITY';
export const SET_FREELANCER_COMPETENCE = 'SET_FREELANCER_COMPETENCE';
export const SET_FACTORS = 'SET_FACTORS';
