// formReducer
export const SET_DEPARTMENT = 'SET_DEPARTMENT';
export const SET_FREELANCER = 'SET_FREELANCER';
export const SET_SUITABILITY = 'SET_SUITABILITY';
export const SET_PIDZ_COMPETENCES = 'SET_PIDZ_COMPETENCES';
export const SET_DEPARTMENT_COMPETENCES = 'SET_DEPARTMENT_COMPETENCES';
export const SET_OTHER_DEPARTMENT_COMPETENCES = 'SET_OTHER_DEPARTMENT_COMPETENCES';
export const SET_FREELANCER_COMPETENCES = 'SET_FREELANCER_COMPETENCES';

// jwtReducer
export const REMOVE_JWT = 'REMOVE_JWT';
export const SET_JWT = 'SET_JWT';

// errorReducer
export const SET_ERROR = 'SET_ERROR';
export const REMOVE_ERROR = 'REMOVE_ERROR';

// onboardingReducer
export const SET_ONBOARDING_STATE = 'SET_ONBOARDING_STATE';
